### Practice

In [7]:
import numpy as np

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [9]:
# derivative of sigmoid function

def sigmoid_prime(x):
    return sigmoid(x) * (1-sigmoid(x))

In [10]:
# input data
x = np.array([0.1,0.3])

# output data/ target
y = 0.2

weights = np.array([-0.8, 0.5])

# learning rate, eta
learningrate = 0.5

In [11]:
# linear combination of node, h=wx
h = np.dot(weights, x)

# neural net output, yhat
yhat = sigmoid(h)

# calculating error
error = y - yhat

# output gradient, f'(h)
f_prime_h = sigmoid_prime(h)

# error term, delta
delta = error * f_prime_h

# gradient descent step
del_w = learningrate * delta * x

In [12]:
del_w

array([-0.0039638 , -0.01189141])

### ASSIGNMENT

In [13]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

### Calculate one gradient descent step for each weight
### Note: Some steps have been consolidated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = np.dot(w,x)

# TODO: Calculate output of neural network
nn_output = sigmoid(h)

# TODO: Calculate error of neural network
error = y - nn_output

# TODO: Calculate the error term
#       Remember, this requires the output gradient, which we haven't
#       specifically added a variable for.
error_term = error * sigmoid_prime(h)

# TODO: Calculate change in weights
del_w = learnrate * error_term * x

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)

Neural Network output:
0.6899744811276125
Amount of Error:
-0.1899744811276125
Change in Weights:
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]


initializing weights randomly for training

In [25]:
input_units = 6

wt = np.random.normal(scale = 1/input_units ** 0.5, size=input_units)
wt

array([-0.59288932,  0.21017603, -0.52217004,  0.21576989,  0.61377087,
       -0.51717789])

In [26]:
wt.shape

(6,)

In [28]:
np.zeros(wt.shape)

array([0., 0., 0., 0., 0., 0.])