Element-wise operations

In [1]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

values

[6, 7, 8, 9, 10]

Numpy way

In [5]:
import numpy as np

In [7]:
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [8]:
arr = np.array([1,2,3,4])
arr*2

array([2, 4, 6, 8])

In [9]:
np.multiply(arr, 2)

array([2, 4, 6, 8])

In [10]:
arr*0

array([0, 0, 0, 0])

In [11]:
arr

array([1, 2, 3, 4])

**Important Reminders About Matrix Multiplication**

- The number of columns in the left matrix must equal the number of rows in the right matrix.

- The answer matrix always has the same number of rows as the left matrix and the same number of columns as the right matrix.

- Order matters. Multiplying A•B is not the same as multiplying B•A.

- Data in the left matrix should be arranged as rows., while data in the right matrix should be arranged as columns.

- If you keep these four points in mind, you should always be able to figure out how to properly arrange your matrix multiplications when building a neural network.

In [12]:
arr.ndim

1

In [15]:
arr = np.array([[1,2],[3,4]])
arr.ndim

2

ASSIGNMENT

# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = None
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = None

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = None

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    pass


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    pass
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    pass


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])

print("Input as Array: {}".format(input_array))

print("Input minus min: {}".format(inputs_minus_min))

print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))

print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))

print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

In [44]:
lst=list(range(1,11))
np.mean(lst)

5.5

In [46]:
lst
np.array(lst)[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
arr = np.array(lst)
print(arr.shape)
print(arr.ndim)

(10,)
1


In [31]:
two_dim = arr[None,:]
two_dim.ndim

2

In [32]:
two_dim

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [36]:
minimal = np.min(two_dim)

In [35]:
np.max(two_dim)

10

In [39]:
two_dim-minimal

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1],[2],[3]])

if a.shape[1]!=b.shape[0]:
    print('not compatible')
else:
    print('good to go')

good to go


In [42]:
a.shape,b.shape

((2, 3), (3, 1))

In [43]:
np.matmul(a,b)

array([[14],
       [32]])

In [52]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2]])

In [57]:
np.matmul(b,a)

array([[ 9, 12, 15]])

In [55]:
b.shape

(1, 2)

In [56]:
a.shape

(2, 3)

In [59]:
b.shape[0]

1

In [60]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [63]:
np.array([lst]).ndim

2

SOLUTION

In [65]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array(inputs)[None, :]
#     or
#     input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1]!=m2.shape[0] and m2.shape[1]!=m1.shape[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if  m1.shape[1] == m2.shape[0]:
        return np.matmul(m1,m2)
    else:
        return np.matmul(m2,m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
