In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [3]:
sigmoid(3)

0.9525741268224334

In [4]:
# network size

N_input = 4
N_hidden = 3
N_output = 2

In [5]:
np.random.seed(42)

In [6]:
# making some fake data

X = np.random.randn(4)

In [7]:
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [8]:
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input,N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden,N_output))

In [9]:
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [10]:
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

### forward pass in the network

In [11]:
hidden_layer_in = np.dot(X, weights_input_to_hidden)

In [12]:
hidden_layer_in

array([-0.34365494, -0.29801368,  0.00097362])

In [13]:
hidden_layer_out = sigmoid(hidden_layer_in)

In [14]:
hidden_layer_out

array([0.41492192, 0.42604313, 0.5002434 ])

In [15]:
output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)

In [16]:
output_layer_in

array([-0.00739221, -0.05842573])

In [17]:
output_layer_out = sigmoid(output_layer_in)

In [18]:
output_layer_out

array([0.49815196, 0.48539772])

In [19]:
print(f'hidden layer output: {hidden_layer_out}')
print(f'output layer output: {output_layer_out}')

hidden layer output: [0.41492192 0.42604313 0.5002434 ]
output layer output: [0.49815196 0.48539772]
