Python is convenient, but it can also be slow. However, it does allow you to access libraries that execute faster code written in languages like C. NumPy is one such library: it provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers - like matrices.

NumPy is a large library and we are only going to scratch the surface of it here. If you plan on doing much math with Python, you should definitely spend some time exploring its [documentation](https://docs.scipy.org/doc/numpy/reference/) to learn more.

In [1]:
import numpy as np

Scalar

Scalars in NumPy are a bit more involved than in Python. Instead of Python’s basic types like int, float, etc., NumPy lets you specify signed and unsigned types, as well as different sizes. So instead of Python’s int, you have access to types like uint8, int8, uint16, int16, and so on.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars. And when you create a NumPy array, you can specify the type - but every item in the array must have the same type. In this regard, NumPy arrays are more like C arrays than Python lists.

If you want to create a NumPy array that holds a scalar, you do so by passing the value to NumPy's array function, like so:

In [2]:
s = np.array(5)

In [3]:
s

array(5)

In [4]:
s.shape

()

In [5]:
print(s)

5


In [6]:
added = s + 5

In [7]:
print(added)

10


In [8]:
type(added)

numpy.int32

In [9]:
type(s)

numpy.ndarray

In [10]:
added.shape

()

Vector

In [11]:
vector = np.array([1,3,5])
vector.shape

(3,)

In [12]:
type(vector)

numpy.ndarray

In [13]:
print(vector)

[1 3 5]


In [14]:
vector[2]

5

In [15]:
vector[0]

1

In [16]:
vector[1]

3

In [17]:
len(vector)

3

In [18]:
vector[1:]

array([3, 5])

Matrices

You create matrices using NumPy's array function, just you did for vectors. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row. So to create a 3x3 matrix containing the numbers one through nine, you could do this:

In [19]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
type(mat)

numpy.ndarray

In [22]:
mat.shape

(3, 3)

In [25]:
mat[1][-1]

6

In [26]:
mat[1][2]

6

In [28]:
mat[1][len(mat[1])-1]

6

Tensors

Tensors are just like vectors and matrices, but they can have more dimensions.

In [35]:
t = np.array([
    [
        [[1],[2]],
        [[3],[4]],
        [[5],[6]]
    ]
])

In [36]:
t.shape

(1, 3, 2, 1)

changing shapes

In [41]:
vec = np.array([1,2,3,4,])
print(vec)
vec.shape

[1 2 3 4]


(4,)

In [42]:
x = vec.reshape(1,4)
print(x)
x.shape

[[1 2 3 4]]


(1, 4)

In [43]:
vec.shape

(4,)

In [44]:
x = vec.reshape(4,1)
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

One more thing about reshaping NumPy arrays: if you see code from experienced NumPy users, you will often see them use a special slicing syntax instead of calling reshape. Using this syntax, the previous two examples would look like this:

In [45]:
x = vec[None, :]

In [46]:
x.shape

(1, 4)

In [47]:
print(x)

[[1 2 3 4]]


In [48]:
x = vec[:, None]
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

Those lines create a slice that looks at all of the items of v but asks NumPy to add a new dimension of size 1 for the associated axis. It may look strange to you now, but it's a common technique so it's good to be aware of it.