**Basic of Tensorflow**

In [0]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [0]:
a = tf.constant([1.2], name='firstnum', dtype=tf.float32)

In [0]:
a

<tf.Tensor 'firstnum_1:0' shape=(1,) dtype=float32>

In [0]:
b = tf.constant([3.2], name='secondnum', dtype=tf.float32)

In [0]:
c = tf.add(a,b, name='total')

In [0]:
c

<tf.Tensor 'total_1:0' shape=(1,) dtype=float32>

In [0]:
tf.constant(5, name='secondnum', dtype=tf.float32)

<tf.Tensor 'secondnum_3:0' shape=() dtype=float32>

In [0]:
with tf.Session() as sess:
  print(sess.run(c))

[4.4]


In [0]:
hello = tf.constant('hello world')

In [0]:
sess = tf.Session()

In [0]:
sess.run(hello)

b'hello world'

In [0]:
sess.close()

read the below error, if you try to use session after closing

In [0]:
# sess.run(hello)

RuntimeError: ignored

In [0]:
with tf.Session() as sess:
  print(sess.run(hello))

b'hello world'


major operations:
1. tf.Constant()
2. tf.Variable()
3. tf.placeholder()

### **Boston Housing Price Prediction**

**Loading libraries**

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
tf.reset_default_graph()

In [0]:
from tensorflow.contrib.learn import datasets

**collecting data**

In [0]:
boston = datasets.load_dataset('boston')

In [0]:
features = np.array(boston.data)
target = np.array(boston.target)

In [146]:
print(f'number of examples: {features.shape[0]}')
print(f'number of features for each examples: {features.shape[1]}')
print(f'shape of actual price data: {target.shape}')

number of examples: 506
number of features for each examples: 13
shape of actual price data: (506,)


**EDA:** **checking data and their shapes**

In [147]:
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [148]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [149]:
features.shape, target.shape

((506, 13), (506,))

In [150]:
features[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [0]:
features[0].shape

(13,)

In [0]:
target[0]

24.0

In [0]:
features.shape[1]

13

In [0]:
target.shape

(506,)

In [0]:
features[0].shape[0]

13

In [0]:
target[0].shape

()

**Building Graph**

In [0]:
# input features
x = tf.placeholder(shape=[None,13], dtype=tf.float32, name='x-input')

# normalize the data
x_n = tf.layers.batch_normalization(x, training=True)

# actual prices of houses
y_ = tf.placeholder(shape=[None], dtype=tf.float32, name='y-input')

**Define weights and Bias**

In [0]:
# weights
W = tf.Variable(tf.zeros(shape=[13,1]), name='weights')

# bias
b = tf.Variable(tf.zeros(shape=[1], name='bias'))

checking tensors

In [135]:
x, y_, W, b

(<tf.Tensor 'x-input:0' shape=(?, 13) dtype=float32>,
 <tf.Tensor 'y-input:0' shape=(?,) dtype=float32>,
 <tf.Variable 'weights:0' shape=(13, 1) dtype=float32_ref>,
 <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>)

Prediction

In [0]:
# using the normalized data rather
y = tf.add(tf.matmul(x_n,W), b, name = 'output')

Loss / Cost function


In [0]:
loss = tf.reduce_mean(tf.square(y-y_), name='loss')

optimizer function

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

**Executing Graph**

In [0]:
sess = tf.Session()

# initializing variables before executing
sess.run(tf.global_variables_initializer())

training_epochs = 100

In [157]:
for epoch in range(training_epochs):
  
  # since we have added placeholer for features and prices/target now actually pasing data
  _, train_loss = sess.run([train_op, loss], feed_dict={x:features, y_:target})

  if epoch%10 == 0:
    print(f'training loss at step {epoch} is {train_loss}')


training loss at step 0 is 592.1470336914062
training loss at step 10 is 231.7105712890625
training loss at step 20 is 117.77751922607422
training loss at step 30 is 84.88145446777344
training loss at step 40 is 84.59691619873047
training loss at step 50 is 84.52581787109375
training loss at step 60 is 84.49124145507812
training loss at step 70 is 84.4708480834961
training loss at step 80 is 84.45761108398438
training loss at step 90 is 84.44850158691406


In [0]:
sess.close()